### ISSUE TITLE
Problem with function

### ISSUE THREAD

**Issue by Qwebeck** [Artinov/weather-app-Qwebeck#2]
I want add to my website feature which hide table and another infirmation ,and when you write city name in form show them
First i add div with class info in which i wrap that information
Then i write class for this block which makes it invisible
After this i add function if in javascript ,which must show this div.info if form is not empty
This function doesnt work 
But when i try to write it in console in browser it start work and div with infi appear
Help , please with this problem ,because function still doesnt work 
Only in console

**Comment by eko24ive** [comment]
Hi @Qwebeck 
Remember you can always use breakpoints to debug your code !

When page opens I see this error in console:
![image](https://cloud.githubusercontent.com/assets/25591824/23593037/346e6dd4-0212-11e7-82f5-72a4adc11362.png)

Which means something happens on line 31, so I'll add breakpoint there and see what its catch:
![image](https://cloud.githubusercontent.com/assets/25591824/23593048/4e941bbe-0212-11e7-8bcb-56b8dfd7aa8c.png)

As you can see `response` variable doesn't have `current` propery, only `error` which means that perhaps something went wrong, lets see what `error` property contain:
![image](https://cloud.githubusercontent.com/assets/25591824/23593061/7735a218-0212-11e7-8f69-c4ba2319bb12.png)

Ok we see that some parameter named `q` is missing, lets think what we can "miss", perhaps town name ?
Indeed, select value is empty:
![image](https://cloud.githubusercontent.com/assets/25591824/23593064/9a527ef6-0212-11e7-979b-d03226130885.png)

Which actually correct, because our page is loaded with empty value and try to send it to server.
We can handle it by adding if statement:
```js
 var getWeatherData = function(){
  var townName = select.value 
  if (select.value == " ") {
    return; //stop function exectuion
  }
```

Now it's ok.
So, we want to show our block when we get weather info, and to be more specific - we want to show it when we get response from server, so let move this commented code:
```js
// if (select.value!=" "){
//   info.setAttribute("style","display:block")
// }
```

Into function which handles response from server, we assigned it to `xhttp.onreadystatechange` by the way. Also let's remove if statement, because we already do same check on upper lines.
Here we go:
```js
      time.innerText = response.location.localtime.split(" ").pop();
      weatherIconsPlaceholders.forEach(function(img){
        img.setAttribute("src","http:" + response.current.condition.icon) }
      )
      info.setAttribute("style","display:block")
    }
```

Now look at this:
![](http://i.imgur.com/bkhqfCf.gif)

**Comment by eko24ive** [comment]
Let me know if you need more specific help !

**Comment by Qwebeck** [comment]
Thank you very much)
